version: '3.8'

services:
  manager-pro:
    image: mechanicf/download-manager:v3.0.0
    container_name: download-manager-pro
    restart: unless-stopped
    ports:
      - "1111:1111"
    # 强制注入安全密钥
    env_file: 
      - .env
    volumes:
      - ./config.json:/opt/Download-Manager/config.json
      - ./downloads.db:/opt/Download-Manager/downloads.db
      - ./logs:/opt/Download-Manager/logs
    environment:
      - TZ=Asia/Shanghai
